version: "3.7"

services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    env_file:
      - "./mysql.env"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        max_attempts: 3
        window: 120s
    networks:
      - keycloak-cluster
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  keycloak-cluster:
    external: true

volumes:
  mysql-data: